project:
  type: website
  preview:
    port: 4200
    browser: true

website:
  title: "Hibiscus Dataset"
  site-path: "/"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Dataset
        href: .
    tools:
      - icon: github
        text: GitHub
        href:
  
  page-footer:
    center: |
      Hibiscus Dataset

  back-to-top-navigation: true
  # repo-url:
  # repo-actions: [edit, issue]
  # repo-link-target: _blank
  page-navigation: true

format:
  html:
    theme:
      light: cosmo
    css: styles/style.css
    toc: false
    sidebar: false
    smooth-scroll: true
    code-overflow: wrap
    output-block-background: true
